local Snacks = require("snacks")
local line_numbers = require("custom.line_numbers")
local keymap = Snacks.keymap.set

line_numbers.setup()
keymap("n", "<C-e>", function()
  Snacks.explorer()
end, { desc = "Open Snacks Explorer" })

keymap("n", ";", ":", { desc = "Enter command mode" })
keymap("n", "<C-t>", function()
  Snacks.terminal()
end, { desc = "Toggle Snacks Terminal" })

keymap("i", "jk", "<Esc>", { desc = "Leave insert mode" })
keymap("t", "jk", [[<C-\><C-n>]], { desc = "Leave terminal insert mode" })
keymap("n", "<leader>ul", function()
  line_numbers.cycle()
end, { desc = "Cycle line number modes" })
keymap("n", "<leader>ff", function()
  Snacks.picker.files()
end, { desc = "Find files" })
keymap("n", "<leader>fg", function()
  Snacks.picker.grep()
end, { desc = "Live grep" })
keymap("n", "<leader>fb", function()
  Snacks.picker.buffers()
end, { desc = "Find buffers" })
keymap("n", "<leader>bd", function()
  Snacks.bufdelete()
end, { desc = "Delete current buffer" })
keymap("n", "<leader>z", function()
  Snacks.zen()
end, { desc = "Toggle Zen mode" })
keymap("n", "<leader>Z", function()
  Snacks.zen.zoom()
end, { desc = "Toggle Zen zoom" })
keymap("n", "<C-h>", "<C-w>h", { desc = "Move to left window" })
keymap("n", "<C-j>", "<C-w>j", { desc = "Move to lower window" })
keymap("n", "<C-k>", "<C-w>k", { desc = "Move to upper window" })
keymap("n", "<C-l>", "<C-w>l", { desc = "Move to right window" })

-- Cycle through bufferline tabs with Ctrl+n / Ctrl+p
--keymap("n", "<C-n>", "<cmd>BufferLineCycleNext<CR>", { desc = "Bufferline: Next buffer" })
--keymap("n", "<C-p>", "<cmd>BufferLineCyclePrev<CR>", { desc = "Bufferline: Previous buffer" })
--keymap("n", "<leader>q", close_buffer_keep_window, { desc = "Close current buffer" })
